Vagrant.configure("2") do |config|
  nodes = [
    { name: "manager01", ip: "192.168.56.10", role: "manager" },
    { name: "worker01", ip: "192.168.56.11", role: "worker" },
    { name: "worker02", ip: "192.168.56.12", role: "worker" }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.box = "ubuntu/bionic64"
      vm.vm.hostname = node[:name]
      vm.vm.network "private_network", ip: node[:ip]
      
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = node[:role] == "manager" ? 4000 : 2048
        vb.cpus = 2
      end

      # Установка Docker
      vm.vm.provision "shell", path: "scripts/install_docker.sh"

      # Если это manager01, выполняем init_swarm.sh
      if node[:role] == "manager"
        vm.vm.network "forwarded_port", guest: 8087, host: 8087
        vm.vm.network "forwarded_port", guest: 8081, host: 8081
        vm.vm.network "forwarded_port", guest: 15672, host: 15672
        vm.vm.network "forwarded_port", guest: 9090, host: 9090
        vm.vm.network "forwarded_port", guest: 3000, host: 3000
        vm.vm.network "forwarded_port", guest: 3100, host: 3100
        vm.vm.provision "file", source: "docker-compose.yaml", destination: "/home/vagrant/docker-compose.yaml"
        vm.vm.provision "file", source: "prometheus.yml", destination: "/home/vagrant/prometheus.yml"
        vm.vm.provision "file", source: "promtail-config.yaml", destination: "/home/vagrant/promtail-config.yaml"
        vm.vm.provision "file", source: "loki-config.yaml", destination: "/home/vagrant/loki-config.yaml"
        vm.vm.provision "file", source: "alerts.rules", destination: "/home/vagrant/alerts.rules"
        vm.vm.provision "file", source: "alertmanager.yml", destination: "/home/vagrant/alertmanager.yml"
        vm.vm.provision "shell", path: "scripts/init_swarm.sh"
      end

      # Если это worker01 или worker02, выполняем join_swarm.sh
      if node[:role] == "worker"
        vm.vm.provision "shell", path: "scripts/join_swarm.sh"
      end
    end
  end
end
